#!/usr/bin/env python3
"""Plot training curves for SO(3)/O cubic SR history.json files."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np


def _to_series(rows: list[dict[str, Any]], key: str) -> np.ndarray:
    vals = [float(r.get(key, np.nan)) for r in rows]
    return np.asarray(vals, dtype=np.float64)


def _safe_min_epoch(values: np.ndarray) -> tuple[int | None, float | None]:
    if values.size == 0 or np.all(~np.isfinite(values)):
        return None, None
    idx = int(np.nanargmin(values))
    return idx + 1, float(values[idx])


def _save_curves(
    train: list[dict[str, Any]],
    val: list[dict[str, Any]],
    out_path: Path,
    log_y: bool = False,
) -> None:
    epochs_t = np.arange(1, len(train) + 1, dtype=np.int32)
    epochs_v = np.arange(1, len(val) + 1, dtype=np.int32)

    fig, axs = plt.subplots(2, 2, figsize=(12, 8), constrained_layout=True)

    def plot_metric(ax, key: str, title: str) -> None:
        yt = _to_series(train, key) if train else np.array([])
        yv = _to_series(val, key) if val else np.array([])
        if yt.size > 0:
            ax.plot(epochs_t, yt, label=f"train {key}", linewidth=2.0)
        if yv.size > 0:
            ax.plot(epochs_v, yv, label=f"val {key}", linewidth=2.0)
        ax.set_title(title)
        ax.set_xlabel("Epoch")
        ax.grid(alpha=0.25)
        if log_y:
            ax.set_yscale("log")
        ax.legend()

    plot_metric(axs[0, 0], "loss", "Loss")
    plot_metric(axs[0, 1], "mse", "Descriptor MSE")
    plot_metric(axs[1, 0], "shell", "Shell Penalty")
    plot_metric(axs[1, 1], "desc_l2", "Descriptor L2 (val)")

    fig.suptitle("SO(3)/O Cubic SR Training Curves")
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot SO3/O cubic SR training history.")
    parser.add_argument(
        "--history",
        type=str,
        required=True,
        help="Path to history.json generated by train_so3_o_cubic_sr_4e6e.py",
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default="",
        help="Output directory for plots (default: history parent directory).",
    )
    args = parser.parse_args()

    history_path = Path(args.history)
    if not history_path.exists():
        raise FileNotFoundError(f"Missing history file: {history_path}")

    with open(history_path, "r", encoding="utf-8") as f:
        history = json.load(f)

    train = list(history.get("train", []))
    val = list(history.get("val", []))

    out_dir = Path(args.out_dir) if args.out_dir else history_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    linear_plot = out_dir / "training_curves.png"
    log_plot = out_dir / "training_curves_log.png"

    _save_curves(train=train, val=val, out_path=linear_plot, log_y=False)
    _save_curves(train=train, val=val, out_path=log_plot, log_y=True)

    val_loss = _to_series(val, "loss") if val else np.array([])
    best_epoch, best_val_loss = _safe_min_epoch(val_loss)

    summary = {
        "history_path": str(history_path),
        "epochs_train": len(train),
        "epochs_val": len(val),
        "best_val_epoch": best_epoch,
        "best_val_loss": best_val_loss,
        "last_train": train[-1] if train else None,
        "last_val": val[-1] if val else None,
        "plots": {
            "training_curves": str(linear_plot),
            "training_curves_log": str(log_plot),
        },
    }
    summary_path = out_dir / "training_summary.json"
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print(f"Saved {linear_plot}")
    print(f"Saved {log_plot}")
    print(f"Saved {summary_path}")
    if best_epoch is not None:
        print(f"Best val loss: {best_val_loss:.6e} at epoch {best_epoch}")


if __name__ == "__main__":
    main()
